### ISSUE TITLE
Packaging Assets

### ISSUE THREAD

**Issue by demonpig** [TeamForbiddenLLC/warfork-assets#2]
I am able to compile Warfork myself but whenever I try to connect to a community server or the forbidden.gg servers, I receive an error message such as 

```
Pure check failed: basefw/modules_21.pk3
```

I checked the console and what I can guess is that if the game does not detect the important pk3 files on the computer (see list below), then the game will attempt to download the assets from [Forbidden.gg's Autoupdate web directory](http://forbidden.gg/warfork/autoupdate/2.1/basewf/).

* data0_21.pk3 
* data0_21pure.pk3
* modules_21.pk3 

When I go to the web directory, I don't see any files beside a beta pk3 file.

I have tried packaging the assets myself using the files in [TeamForbiddenLLC/warfork-assets-sources repo](https://github.com/TeamForbiddenLLC/warfork-assets-sources/tree/master/packaging). But even those files don't appear to be up-to-date as I have to modify them in order complete the process of creating pk3 files.

Another method that I have used is just simply clone the warfork-assets repo into the basefw directory. I still receive the error message above when connecting to community servers.

Is there a process for packaging the assets that can be shard publicly?

**Comment by Warfork** [comment]
don't pack any of the files in /weapons/
